CREATE TABLE IF NOT EXISTS users (
user_id    INTEGER PRIMARY KEY AUTOINCREMENT,
first_name TEXT NOT NULL DEFAULT 'Unknown',
last_name  TEXT NOT NULL DEFAULT 'Unknown',
email      TEXT NOT NULL DEFAULT 'Unknown'
);
