CREATE TABLE IF NOT EXISTS iplist (
ip_id   INTEGER PRIMARY KEY,
user_id INTEGER,
ipValue TEXT,
ipValid INTEGER DEFAULT TRUE,
firstAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
logincount INTEGER NOT NULL DEFAULT 1
);