CREATE TABLE IF NOT EXISTS connection (
connection_id  INTEGER PRIMARY KEY,
user_id  INTEGER,
createdatts TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
thislogints TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
lastlogints TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
createdatip TEXT NOT NULL, 
lastloginip TEXT NOT NULL,
thisloginip TEXT NOT NULL,
logincount    INTEGER NOT NULL DEFAULT 1,
vpn_check     INTEGER NOT NULL DEFAULT FALSE,
vpn_valid     INTEGER NOT NULL DEFAULT FALSE
);
--> To UNIQUE for createdatip